name: Docker Image CI
## this one doesn't publish to any registry
## thus the docker-publish.yml is more useful.

on:
  push:
    branches: [ disabled--master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag r4eta:$(date +%Y%m%d_%H%M)
